export const WORDS = [
  {id:'n5-001',level:'N5',word:'猫',reading:'ねこ',meaning:'고양이',example:'猫が好きです。',exampleKo:'고양이를 좋아합니다.',tags:['동물']},
  {id:'n5-002',level:'N5',word:'犬',reading:'いぬ',meaning:'개',example:'犬と散歩します。',exampleKo:'개와 산책합니다.',tags:['동물']},
  {id:'n5-003',level:'N5',word:'水',reading:'みず',meaning:'물',example:'水を飲みます。',exampleKo:'물을 마십니다.',tags:['생활']},
  {id:'n5-004',level:'N5',word:'山',reading:'やま',meaning:'산',example:'山がきれいです。',exampleKo:'산이 아름답습니다.',tags:['자연']},
  {id:'n5-005',level:'N5',word:'川',reading:'かわ',meaning:'강',example:'川のそばを歩きます。',exampleKo:'강 옆을 걷습니다.',tags:['자연']},
  {id:'n5-006',level:'N5',word:'空',reading:'そら',meaning:'하늘',example:'空が青いです。',exampleKo:'하늘이 파랗습니다.',tags:['자연']},
  {id:'n5-007',level:'N5',word:'雨',reading:'あめ',meaning:'비',example:'今日は雨です。',exampleKo:'오늘은 비가 옵니다.',tags:['날씨']},
  {id:'n5-008',level:'N5',word:'雪',reading:'ゆき',meaning:'눈',example:'雪が降っています。',exampleKo:'눈이 내리고 있습니다.',tags:['날씨']},
  {id:'n5-009',level:'N5',word:'今日',reading:'きょう',meaning:'오늘',example:'今日は休みです。',exampleKo:'오늘은 휴일입니다.',tags:['시간']},
  {id:'n5-010',level:'N5',word:'明日',reading:'あした',meaning:'내일',example:'明日会いましょう。',exampleKo:'내일 만나요.',tags:['시간']},
  {id:'n5-011',level:'N5',word:'昨日',reading:'きのう',meaning:'어제',example:'昨日は忙しかったです。',exampleKo:'어제는 바빴습니다.',tags:['시간']},
  {id:'n5-012',level:'N5',word:'朝',reading:'あさ',meaning:'아침',example:'朝ご飯を食べます。',exampleKo:'아침밥을 먹습니다.',tags:['시간']},
  {id:'n5-013',level:'N5',word:'夜',reading:'よる',meaning:'밤',example:'夜に本を読みます。',exampleKo:'밤에 책을 읽습니다.',tags:['시간']},
  {id:'n5-014',level:'N5',word:'学校',reading:'がっこう',meaning:'학교',example:'学校へ行きます。',exampleKo:'학교에 갑니다.',tags:['장소']},
  {id:'n5-015',level:'N5',word:'先生',reading:'せんせい',meaning:'선생님',example:'先生に質問します。',exampleKo:'선생님께 질문합니다.',tags:['사람']},
  {id:'n5-016',level:'N5',word:'学生',reading:'がくせい',meaning:'학생',example:'私は学生です。',exampleKo:'저는 학생입니다.',tags:['사람']},
  {id:'n5-017',level:'N5',word:'友達',reading:'ともだち',meaning:'친구',example:'友達と映画を見ます。',exampleKo:'친구와 영화를 봅니다.',tags:['사람']},
  {id:'n5-018',level:'N5',word:'家',reading:'いえ',meaning:'집',example:'家に帰ります。',exampleKo:'집에 돌아갑니다.',tags:['장소']},
  {id:'n5-019',level:'N5',word:'駅',reading:'えき',meaning:'역',example:'駅で待っています。',exampleKo:'역에서 기다리고 있습니다.',tags:['장소']},
  {id:'n5-020',level:'N5',word:'電車',reading:'でんしゃ',meaning:'전철',example:'電車に乗ります。',exampleKo:'전철을 탑니다.',tags:['교통']},
  {id:'n5-021',level:'N5',word:'車',reading:'くるま',meaning:'자동차',example:'車を運転します。',exampleKo:'자동차를 운전합니다.',tags:['교통']},
  {id:'n5-022',level:'N5',word:'本',reading:'ほん',meaning:'책',example:'本を二冊買いました。',exampleKo:'책을 두 권 샀습니다.',tags:['물건']},
  {id:'n5-023',level:'N5',word:'食べる',reading:'たべる',meaning:'먹다',example:'りんごを食べます。',exampleKo:'사과를 먹습니다.',tags:['동사']},
  {id:'n5-024',level:'N5',word:'飲む',reading:'のむ',meaning:'마시다',example:'コーヒーを飲みます。',exampleKo:'커피를 마십니다.',tags:['동사']},
  {id:'n5-025',level:'N5',word:'見る',reading:'みる',meaning:'보다',example:'テレビを見ます。',exampleKo:'텔레비전을 봅니다.',tags:['동사']},
  {id:'n5-026',level:'N5',word:'聞く',reading:'きく',meaning:'듣다 / 묻다',example:'音楽を聞きます。',exampleKo:'음악을 듣습니다.',tags:['동사']},
  {id:'n5-027',level:'N5',word:'話す',reading:'はなす',meaning:'말하다',example:'日本語で話します。',exampleKo:'일본어로 말합니다.',tags:['동사']},
  {id:'n5-028',level:'N5',word:'読む',reading:'よむ',meaning:'읽다',example:'新聞を読みます。',exampleKo:'신문을 읽습니다.',tags:['동사']},
  {id:'n5-029',level:'N5',word:'書く',reading:'かく',meaning:'쓰다',example:'名前を書いてください。',exampleKo:'이름을 써 주세요.',tags:['동사']},
  {id:'n5-030',level:'N5',word:'行く',reading:'いく',meaning:'가다',example:'東京へ行きます。',exampleKo:'도쿄에 갑니다.',tags:['동사']},
  {id:'n5-031',level:'N5',word:'来る',reading:'くる',meaning:'오다',example:'友達が来ます。',exampleKo:'친구가 옵니다.',tags:['동사']},
  {id:'n5-032',level:'N5',word:'帰る',reading:'かえる',meaning:'돌아가다',example:'六時に帰ります。',exampleKo:'6시에 돌아갑니다.',tags:['동사']},
  {id:'n5-033',level:'N5',word:'大きい',reading:'おおきい',meaning:'크다',example:'大きい犬ですね。',exampleKo:'큰 개네요.',tags:['형용사']},
  {id:'n5-034',level:'N5',word:'小さい',reading:'ちいさい',meaning:'작다',example:'小さい店です。',exampleKo:'작은 가게입니다.',tags:['형용사']},
  {id:'n5-035',level:'N5',word:'新しい',reading:'あたらしい',meaning:'새롭다',example:'新しい靴を買いました。',exampleKo:'새 신발을 샀습니다.',tags:['형용사']},
  {id:'n5-036',level:'N5',word:'古い',reading:'ふるい',meaning:'오래되다 / 낡다',example:'古い写真を見つけました。',exampleKo:'오래된 사진을 찾았습니다.',tags:['형용사']},
  {id:'n5-037',level:'N5',word:'高い',reading:'たかい',meaning:'비싸다 / 높다',example:'この時計は高いです。',exampleKo:'이 시계는 비쌉니다.',tags:['형용사']},
  {id:'n5-038',level:'N5',word:'安い',reading:'やすい',meaning:'싸다',example:'この店は安いです。',exampleKo:'이 가게는 쌉니다.',tags:['형용사']},
  {id:'n5-039',level:'N5',word:'好き',reading:'すき',meaning:'좋아함',example:'日本の料理が好きです。',exampleKo:'일본 음식을 좋아합니다.',tags:['감정']},
  {id:'n5-040',level:'N5',word:'元気',reading:'げんき',meaning:'건강함 / 활기참',example:'お元気ですか。',exampleKo:'잘 지내세요?',tags:['상태']},
  {id:'n4-001',level:'N4',word:'約束',reading:'やくそく',meaning:'약속',example:'友達と約束があります。',exampleKo:'친구와 약속이 있습니다.',tags:['생활']},
  {id:'n4-002',level:'N4',word:'準備',reading:'じゅんび',meaning:'준비',example:'旅行の準備をします。',exampleKo:'여행 준비를 합니다.',tags:['생활']},
  {id:'n4-003',level:'N4',word:'予定',reading:'よてい',meaning:'예정 / 계획',example:'週末の予定は何ですか。',exampleKo:'주말 계획은 무엇인가요?',tags:['시간']},
  {id:'n4-004',level:'N4',word:'必要',reading:'ひつよう',meaning:'필요',example:'パスポートが必要です。',exampleKo:'여권이 필요합니다.',tags:['상태']},
  {id:'n4-005',level:'N4',word:'理由',reading:'りゆう',meaning:'이유',example:'理由を教えてください。',exampleKo:'이유를 알려 주세요.',tags:['추상']},
  {id:'n4-006',level:'N4',word:'経験',reading:'けいけん',meaning:'경험',example:'日本で働いた経験があります。',exampleKo:'일본에서 일한 경험이 있습니다.',tags:['추상']},
  {id:'n4-007',level:'N4',word:'説明',reading:'せつめい',meaning:'설명',example:'先生が文法を説明します。',exampleKo:'선생님이 문법을 설명합니다.',tags:['학습']},
  {id:'n4-008',level:'N4',word:'相談',reading:'そうだん',meaning:'상담 / 의논',example:'先生に相談しました。',exampleKo:'선생님께 상담했습니다.',tags:['생활']},
  {id:'n4-009',level:'N4',word:'連絡',reading:'れんらく',meaning:'연락',example:'後で連絡します。',exampleKo:'나중에 연락하겠습니다.',tags:['생활']},
  {id:'n4-010',level:'N4',word:'心配',reading:'しんぱい',meaning:'걱정',example:'あまり心配しないでください。',exampleKo:'너무 걱정하지 마세요.',tags:['감정']},
  {id:'n4-011',level:'N4',word:'安心',reading:'あんしん',meaning:'안심',example:'無事だと聞いて安心しました。',exampleKo:'무사하다고 들어서 안심했습니다.',tags:['감정']},
  {id:'n4-012',level:'N4',word:'残念',reading:'ざんねん',meaning:'아쉬움 / 유감',example:'行けなくて残念です。',exampleKo:'가지 못해서 아쉽습니다.',tags:['감정']},
  {id:'n4-013',level:'N4',word:'十分',reading:'じゅうぶん',meaning:'충분함',example:'時間は十分あります。',exampleKo:'시간은 충분히 있습니다.',tags:['상태']},
  {id:'n4-014',level:'N4',word:'最近',reading:'さいきん',meaning:'최근',example:'最近忙しいです。',exampleKo:'최근 바쁩니다.',tags:['시간']},
  {id:'n4-015',level:'N4',word:'途中',reading:'とちゅう',meaning:'도중',example:'学校へ行く途中で会いました。',exampleKo:'학교에 가는 도중에 만났습니다.',tags:['시간']},
  {id:'n4-016',level:'N4',word:'場合',reading:'ばあい',meaning:'경우',example:'雨の場合は中止です。',exampleKo:'비가 올 경우에는 취소입니다.',tags:['추상']},
  {id:'n4-017',level:'N4',word:'間に合う',reading:'まにあう',meaning:'시간에 맞다',example:'電車に間に合いました。',exampleKo:'전철 시간에 맞았습니다.',tags:['동사']},
  {id:'n4-018',level:'N4',word:'続ける',reading:'つづける',meaning:'계속하다',example:'毎日勉強を続けます。',exampleKo:'매일 공부를 계속합니다.',tags:['동사']},
  {id:'n4-019',level:'N4',word:'決める',reading:'きめる',meaning:'정하다',example:'旅行の日を決めました。',exampleKo:'여행 날짜를 정했습니다.',tags:['동사']},
  {id:'n4-020',level:'N4',word:'比べる',reading:'くらべる',meaning:'비교하다',example:'二つの商品を比べます。',exampleKo:'두 상품을 비교합니다.',tags:['동사']},
  {id:'n4-021',level:'N4',word:'増える',reading:'ふえる',meaning:'늘다',example:'外国人の客が増えました。',exampleKo:'외국인 손님이 늘었습니다.',tags:['동사']},
  {id:'n4-022',level:'N4',word:'減る',reading:'へる',meaning:'줄다',example:'仕事が少し減りました。',exampleKo:'일이 조금 줄었습니다.',tags:['동사']},
  {id:'n4-023',level:'N4',word:'慣れる',reading:'なれる',meaning:'익숙해지다',example:'日本の生活に慣れました。',exampleKo:'일본 생활에 익숙해졌습니다.',tags:['동사']},
  {id:'n4-024',level:'N4',word:'選ぶ',reading:'えらぶ',meaning:'고르다',example:'好きな色を選んでください。',exampleKo:'좋아하는 색을 골라 주세요.',tags:['동사']},
  {id:'n4-025',level:'N4',word:'伝える',reading:'つたえる',meaning:'전하다',example:'先生に伝えておきます。',exampleKo:'선생님께 전해 두겠습니다.',tags:['동사']},
  {id:'n4-026',level:'N4',word:'手伝う',reading:'てつだう',meaning:'돕다',example:'母の料理を手伝います。',exampleKo:'어머니의 요리를 돕습니다.',tags:['동사']},
  {id:'n4-027',level:'N4',word:'片付ける',reading:'かたづける',meaning:'정리하다',example:'部屋を片付けます。',exampleKo:'방을 정리합니다.',tags:['동사']},
  {id:'n4-028',level:'N4',word:'見つける',reading:'みつける',meaning:'찾아내다',example:'いい店を見つけました。',exampleKo:'좋은 가게를 찾았습니다.',tags:['동사']},
  {id:'n4-029',level:'N4',word:'眠い',reading:'ねむい',meaning:'졸리다',example:'今日はとても眠いです。',exampleKo:'오늘은 매우 졸립니다.',tags:['상태']},
  {id:'n4-030',level:'N4',word:'厳しい',reading:'きびしい',meaning:'엄격하다 / 심하다',example:'冬の寒さは厳しいです。',exampleKo:'겨울 추위가 심합니다.',tags:['형용사']}
];

export const LEVELS = ['N5','N4'];
export const DAILY_GOAL = 10;
